security:
    encoders:
              FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    acl:
        connection: default    
    providers:
        fos_userbundle:
                 id: fos_user.user_provider.username_email      

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                use_forward: false
                check_path: fos_user_security_check
                failure_path: null
                remember_me: true
            remember_me:
                   key :   %secret%
                   lifetime:  3000000000
                   path:    /profile
                   domain: ~
            logout:
                  path: fos_user_security_logout
                  target: /login
            anonymous:    true       

    access_control:
       - { path: ^/profile, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin, role: ROLE_ADMIN }
